### ISSUE TITLE
Flatpak repo

### ISSUE THREAD

**Issue by vrutkovs** [RussianFedora/server-config#12]
nginx + отдельный домен + rsync для загрузки.

Потребуются отдельные пользователи с ограниченными правами

**Comment by gasinvein** [comment]
Можно использовать `flat-manager` (и, соответственно, `flat-manager-client` для загрузки). Лучше тем, что позволяет выдавать токены с ограниченными правами. Хуже тем, что недоступен в репозиториях.

**Comment by vrutkovs** [comment]
Думаю flat-manager запустим в контейнере. Ему еще нужен postgresql (тоже в контейнере) + nginx proxy. В идеале нужно еще ограничить размер репозитория, но это можно отложить
