### ISSUE TITLE
Antispam bot for Telegram groups

### ISSUE THREAD

**Issue by xvitaly** [RussianFedora/server-config#14]
В связи с прекращением работы ботов, которые хостились на моей VPS, нужно захостить их на данном сервере.

Полные исходники бота: https://github.com/xvitaly/ecasbot

Ветка **master** пригодна для постоянного использования. Ветка **dev** может содержать breaking changes в виде изменения версий схемы файла конфигурации например.

Конфиг бота, который использовался ранее на VPS, конвертированный в формат текущей версии:
[ecasbot.zip](https://github.com/RussianFedora/server-config/files/4807625/ecasbot.zip)

Для запуска нужно сделать следующее:

- [ ] создать бота у BotFather в Telegram и получить уникальный токен;
- [ ] развернуть бота из Git или при помощи RPM пакета;
- [ ] прописать в конфиге переменных окружения бота полученный токен;
- [ ] прописать в конфиге бота ID аккаунтов администраторов (эти люди будут иметь неограниченные полномочия по настройке бота, смогут добавлять и удалять новые ключевые слова, настраивать приоритеты, а также получат права самого бота в каждом чате с ним даже если у них там нет собственных полномочий);
- [ ] настроить автоматический запуск средствами systemd (юниты предоставляются);
- [ ] добавить бота в чаты;
- [ ] после добавления во все нужные чаты рекомендуется через BotFather включить для бота режим приватности, чтобы его не могли добавить в чужие чаты, т.к. это создаст лишнюю нагрузку.

**Comment by vrutkovs** [comment]
>прописать в конфиге переменных окружения бота полученный токен

Можем использовать мой бот - (@)vrutkovs_antispam_bot. Не уверен что телеграм позволит использовать токен из двух мест

> прописать в конфиге бота ID аккаунтов администраторов

@tim77 @Vascom - сможете быть администраторами?

**Comment by Vascom** [comment]
А мы и так админы же.

**Comment by xvitaly** [comment]
> А мы и так админы же.

У бота есть свои администраторы. Это даёт доступ к специальным командам вроде `/sw_add`.

> Можем использовать мой бот - (@)vrutkovs_antispam_bot. Не уверен что телеграм позволит использовать токен из двух мест

Один токен использовать для двух ботов нельзя. Первого выкинет с сервера, затем они начнут гонку за токен. Лучше создать свой.

Кстати, освободился логин **ecasbot**. Лучше его и занять.

**Comment by Hubbitus** [comment]
[Quote](https://matrix.to/#/!HRTZtklkwBCcsGDhgU:matrix.org/$1593340422195900wiFwu:matrix.org?via=matrix.org&via=russianfedora.online&via=skoryh.com) xvitaly:

> Сорцы бота: https://github.com/xvitaly/ecasbot
> Готовые RPM: https://copr.fedorainfracloud.org/coprs/xvitaly/ecrepo/package/ecasbot/

**Comment by Hubbitus** [comment]
>  развернуть бота из Git или при помощи RPM пакета;
> прописать в конфиге переменных окружения бота полученный токен;

В матриксе же обсудили что контейнер делаем?

**Comment by vrutkovs** [comment]
В #17 сделал простую роль для запуска бота в контейнере:
* в vault прописал токен бота `russian_fedora_bot`
* в https://github.com/vrutkovs/ecasbot/tree/master-dockerfile создал Dockerfile, настроил автоматическую сборку в Quay
  Приходится собирать контейнер, потому как COPR билды есть только для F32/Rawhide. Я беспокоился о том, что придется лишний раз собирать контейнер, но об этом заботится quay

**Comment by xvitaly** [comment]
> Приходится собирать контейнер, потому как COPR билды есть только для F32/Rawhide. Я беспокоился о том, что придется лишний раз собирать контейнер, но об этом заботится quay

Какие нужны? Это не проблема собрать.

**Comment by vrutkovs** [comment]
Сам сервер на centos7, но возможно мы переедем на centos 8. Думаю запуск в контейнере упростит задачу - чтобы не пришлось тянут свежий питон и т.д.

Бот запущен на сервере, закрываю

**Comment by Hubbitus** [comment]
@vrutkovs, выше вашего коммита был коммит контейнера и автобилда нв докерхабе. Если сами делать задачу взялись, хоть бы сказазали, ответили на вопрос...

**Comment by vrutkovs** [comment]
Пардон, но выше есть комментарий (от 6го июля) где я ответил на вопрос, как мне казалось.

Автобилд вещь полезная, но там уже две недели нет билдов - как он настроен?

**Comment by Hubbitus** [comment]
По коммитам в реп. Но наверное уже нет смысла если всё готово...
Сорри, если подвёл, хотел помочь, но вроде ответа ждал. В следующий раз наверное стоит в телеграмме пнуть.

**Comment by vrutkovs** [comment]
>По коммитам в реп.

Но в твой форк, а не от @xvitaly, верно? В общем, я столкнулся с такой же проблемой - думаю нам стоит перенести бота в эту организацию на гитхабе (или добавить спец ключ. от Quay для автосборки в ecasbot репозиторий).

>В следующий раз наверное стоит в тееграмме пнуть.

Да, это будет проще. Мы организовываемся в https://matrix.to/#/#fedora-ru-org:matrix.org:russianfedora.online, но способ общения не принципиален

**Comment by Hubbitus** [comment]
> Но в твой форк, а не от @xvitaly, верно? В общем, я столкнулся с такой же проблемой - думаю нам стоит перенести бота в эту организацию на гитхабе (или добавить спец ключ. от Quay для автосборки в ecasbot репозиторий).
Там не форк, по сути реп с докерфайлом и автобилд, законнекценный в докерхабе на реп. https://docs.docker.com/docker-hub/builds/

Если речь про то что он не следит за появлением новых версий в COPR, то нет, не следит. Это можно сделать, но не кажется особо нужным.

> Да, это будет проще. Мы организовываемся в https://matrix.to/#/#fedora-ru-org:matrix.org:russianfedora.online, но способ общения не принципиален

Точно. Там и начинали. Я туда не часто захожу, не успеваю. Но постараюсь в следующий раз.
