### ISSUE TITLE
Cockpit

### ISSUE THREAD

**Issue by vrutkovs** [RussianFedora/server-config#15]
На сервере уже запущено несколько контейнеров (matrix+prometheus+grafana), но мы планируем добавить еще сервисы. Думаю стоит установить на сервере cockpit чтобы мы могли быстро посмотреть статус сервера (изменения я бы предпочел делать через ansible)

@bookwar @Vascom @xvitaly что думаете?

**Comment by Vascom** [comment]
Почему бы и нет?

**Comment by xvitaly** [comment]
Было бы неплохо.

**Comment by vrutkovs** [comment]
Задеплоил. Пользователи из https://github.com/RussianFedora/server-config/blob/master/inventory/host_vars/build-server.yaml#L12-L22 должны установить себе пароль и могут зайти на порту 9090
