### ISSUE TITLE
Не грузятся изображения

### ISSUE THREAD

**Issue by ivan-tretyak** [RussianFedora/server-config#24]
После обновления сервера от 26.02.2021 перестали грузится любые изображения с сервера. Не грузятся аватары пользователей, изображения чатов, изображения в чатах, нельзя отправить изображения в чат, значки сообществ. Чат выглядит как на приложенном ниже скриншоте. При попытке нажать на ссылку для скачивания изображения, выдает:
```
No Such Resource

Sorry. No luck finding that resource.
```
Cкриншот.
![image](https://user-images.githubusercontent.com/34531674/109318345-c0182980-785e-11eb-9363-74638bbc9497.png)

**Comment by vrutkovs** [comment]
Fixed in https://github.com/RussianFedora/server-config/commit/08691e548d24660150d59ff6b20363a3bc562abb
