### ISSUE TITLE
Федерацию в отдельный процесс

### ISSUE THREAD

**Issue by xvitaly** [RussianFedora/server-config#8]
Вынести федерацию в отдельный процесс, т.к. лаги matrix.org приводят к рассинхронизации истории и потере нитей обсуждения.

**Comment by vrutkovs** [comment]
Ждём https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/456

**Comment by vrutkovs** [comment]
https://github.com/RussianFedora/server-config/commit/129417912873e8bbaf330691ec599d3eb1314630
